In [2]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

In [17]:
combine = pd.read_csv("resources/nflcombine.csv")

In [33]:
combine["Forty"].min()

4.22

In [34]:
combine[combine["Forty"] == 4.22]

,Player,Pos,Ht,Wt,Forty,Vertical,BenchReps,BroadJump,Cone,Shuttle,Year,Pfr_ID,AV,Team,Round,Pick
914,Donte' Stallworth,WR,72,197,4.22,NaN,NaN,NaN,NaN,NaN,2002,StalDo00,19.0,New Orleans Saints,1.0,13.0
5805,John Ross,WR,71,188,4.22,37.0,NaN,133.0,NaN,NaN,2017,RossJo00,0.0,Cincinnati Bengals,1.0,9.0

In [39]:
combine.pivot_table(index="Player", columns="Pos", values="Forty")

Pos,C,CB,DB,DE,DT,EDGE,FB,FS,G,ILB,...,OL,OLB,OT,P,QB,RB,S,SS,TE,WR
Player,,,,,,,,,,,,,,,,,,,,,
A'Shawn Robinson,NaN,NaN,NaN,NaN,5.20,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A.C. Leonard,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.50,NaN
A.D. Denham,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.69,NaN
A.J. Cann,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A.J. Davis,NaN,4.56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zeke Motta,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.75,NaN,NaN
Zeron Flemister,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.72,NaN
Ziggy Ansah,NaN,NaN,NaN,4.56,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Ziggy Hood,NaN,NaN,NaN,NaN,4.83,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zoltan Mesko,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,4.79,NaN,NaN,NaN,NaN,NaN,NaN